# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83570c336e2979347796828f713901dde2702ddafea2996dd0c0793f9fd4a7522a99d337670f4ce8f2b8506bb49d530b8adf04b4c04f838041e673559028c457

test:
  secret_key_base: c656091c1778ee56fd05ca6b53c88842e44f7862929fbc189809f09245e6c5b57cb0c3c9b72f9788398456b49f5f1f3a79cf254443dd62ad2166414cc69b65ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
